### ISSUE TITLE
key error with more recent pyluwen

### ISSUE THREAD

**Issue by warthog9** [tenstorrent/tt-burnin#4]
```
(venv) root@orko:~/git/tt-burnin# tt-burnin
 Detected Chips: 1
 Detecting ARC: |
 Detecting DRAM: |
 [] ETH: |
┏━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Pci Dev ID ┃ Board Type ┃ Device Series ┃ Board Number    ┃ Coordinates ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ 0          │ grayskull  │ e75           │ 10000741171[redacted] │ N/A         │
└────────────┴────────────┴───────────────┴─────────────────┴─────────────┘
 Resetting devices on host...
 Re-initializing boards after reset....
 Detected Chips: 1
 Detecting ARC: |
 Detecting DRAM: |
 [] ETH: |

 Starting TT-Burnin workload on all boards. WARNING: Opening SMI might cause unexpected behavior

 Stopping TT-Burnin workload on all boards.

 Resetting devices on host...
 Re-initializing boards after reset....
 Detected Chips: 1
 Detecting ARC: |
 Detecting DRAM: |
 [] ETH: |
Traceback (most recent call last):
  File "/root/venv/bin/tt-burnin", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/venv/lib64/python3.12/site-packages/tt_burnin/main.py", line 224, in main
    with Live(Group(generate_table(devices), text), refresh_per_second=10) as live:
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib64/python3.12/site-packages/tt_burnin/utils.py", line 207, in generate_table
    current = int(hex(telem["smbus_tx_tdc"]), 16) & 0xFFFF
                      ~~~~~^^^^^^^^^^^^^^^^
KeyError: 'smbus_tx_tdc'
```

**Comment by JS-Choi513** [comment]
I got the same issue, 
So, I created other conda envs for `tt-burnin`, and installed `tt-burnin` via pip3.
Then I removed `smbus_tx_` at all key strings in `/root/venv/lib64/python3.12/site-packages/tt_burnin/utils.py` file.
It works now. Please match the key in `telem` dict.

**Comment by TTDRosen** [comment]
Hey Guys, thanks for working around this issue. As of burning 0.2.0 (merged last week) I updated the dictionary keys to drop the smbus_tx prefix.
